/*
 * owenpeterson.ca
 * This is the server for my personal website.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: owen.a.peterson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ca.owenpeterson.web.api.client.api;

import ca.owenpeterson.web.api.client.model.ApiDefaultError;
import ca.owenpeterson.web.api.client.model.ApiServerStatusResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * Gets the current status of the server.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getServerStatusTest() {
        ApiServerStatusResponse response = api.getServerStatus();

        // TODO: test validations
    }
    
}
