/*
 * owenpeterson.ca
 * This is the server for my personal website.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: owen.a.peterson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ca.owenpeterson.web.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ApiServerStatusResponse
 */
@JsonPropertyOrder({
  ApiServerStatusResponse.JSON_PROPERTY_DB_STATUS,
  ApiServerStatusResponse.JSON_PROPERTY_DB_START_TIME
})
@JsonTypeName("ApiServerStatusResponse")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ApiServerStatusResponse {
  public static final String JSON_PROPERTY_DB_STATUS = "db_status";
  private String dbStatus;

  public static final String JSON_PROPERTY_DB_START_TIME = "db_start_time";
  private OffsetDateTime dbStartTime;

  public ApiServerStatusResponse() { 
  }

  public ApiServerStatusResponse dbStatus(String dbStatus) {
    
    this.dbStatus = dbStatus;
    return this;
  }

   /**
   * Get dbStatus
   * @return dbStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DB_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDbStatus() {
    return dbStatus;
  }


  @JsonProperty(JSON_PROPERTY_DB_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDbStatus(String dbStatus) {
    this.dbStatus = dbStatus;
  }


  public ApiServerStatusResponse dbStartTime(OffsetDateTime dbStartTime) {
    
    this.dbStartTime = dbStartTime;
    return this;
  }

   /**
   * Get dbStartTime
   * @return dbStartTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DB_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDbStartTime() {
    return dbStartTime;
  }


  @JsonProperty(JSON_PROPERTY_DB_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDbStartTime(OffsetDateTime dbStartTime) {
    this.dbStartTime = dbStartTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiServerStatusResponse apiServerStatusResponse = (ApiServerStatusResponse) o;
    return Objects.equals(this.dbStatus, apiServerStatusResponse.dbStatus) &&
        Objects.equals(this.dbStartTime, apiServerStatusResponse.dbStartTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dbStatus, dbStartTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiServerStatusResponse {\n");
    sb.append("    dbStatus: ").append(toIndentedString(dbStatus)).append("\n");
    sb.append("    dbStartTime: ").append(toIndentedString(dbStartTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

