/*
 * owenpeterson.ca
 * This is the server for my personal website.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: owen.a.peterson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ca.owenpeterson.web.api.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ApiServerStatus
 */
@JsonPropertyOrder({
  ApiServerStatus.JSON_PROPERTY_DATABASE_STATUS,
  ApiServerStatus.JSON_PROPERTY_DATABASE_START_TIME
})
@JsonTypeName("ApiServerStatus")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ApiServerStatus {
  public static final String JSON_PROPERTY_DATABASE_STATUS = "databaseStatus";
  private String databaseStatus;

  public static final String JSON_PROPERTY_DATABASE_START_TIME = "databaseStartTime";
  private OffsetDateTime databaseStartTime;

  public ApiServerStatus() { 
  }

  public ApiServerStatus databaseStatus(String databaseStatus) {
    
    this.databaseStatus = databaseStatus;
    return this;
  }

   /**
   * Get databaseStatus
   * @return databaseStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATABASE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDatabaseStatus() {
    return databaseStatus;
  }


  @JsonProperty(JSON_PROPERTY_DATABASE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatabaseStatus(String databaseStatus) {
    this.databaseStatus = databaseStatus;
  }


  public ApiServerStatus databaseStartTime(OffsetDateTime databaseStartTime) {
    
    this.databaseStartTime = databaseStartTime;
    return this;
  }

   /**
   * Get databaseStartTime
   * @return databaseStartTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATABASE_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDatabaseStartTime() {
    return databaseStartTime;
  }


  @JsonProperty(JSON_PROPERTY_DATABASE_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatabaseStartTime(OffsetDateTime databaseStartTime) {
    this.databaseStartTime = databaseStartTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiServerStatus apiServerStatus = (ApiServerStatus) o;
    return Objects.equals(this.databaseStatus, apiServerStatus.databaseStatus) &&
        Objects.equals(this.databaseStartTime, apiServerStatus.databaseStartTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(databaseStatus, databaseStartTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiServerStatus {\n");
    sb.append("    databaseStatus: ").append(toIndentedString(databaseStatus)).append("\n");
    sb.append("    databaseStartTime: ").append(toIndentedString(databaseStartTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

