/*
 * owenpeterson.ca
 * This is the server for my personal website.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: owen.a.peterson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ca.owenpeterson.web.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import ca.owenpeterson.web.api.client.model.ApiDefaultError;
import ca.owenpeterson.web.api.client.model.ApiServerStatus;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ApiServerStatusResponse
 */
@JsonPropertyOrder({
  ApiServerStatusResponse.JSON_PROPERTY_SERVER_STATUS,
  ApiServerStatusResponse.JSON_PROPERTY_ERROR
})
@JsonTypeName("ApiServerStatusResponse")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ApiServerStatusResponse {
  public static final String JSON_PROPERTY_SERVER_STATUS = "serverStatus";
  private ApiServerStatus serverStatus;

  public static final String JSON_PROPERTY_ERROR = "error";
  private ApiDefaultError error;

  public ApiServerStatusResponse() { 
  }

  public ApiServerStatusResponse serverStatus(ApiServerStatus serverStatus) {
    
    this.serverStatus = serverStatus;
    return this;
  }

   /**
   * Get serverStatus
   * @return serverStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SERVER_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ApiServerStatus getServerStatus() {
    return serverStatus;
  }


  @JsonProperty(JSON_PROPERTY_SERVER_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServerStatus(ApiServerStatus serverStatus) {
    this.serverStatus = serverStatus;
  }


  public ApiServerStatusResponse error(ApiDefaultError error) {
    
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ApiDefaultError getError() {
    return error;
  }


  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(ApiDefaultError error) {
    this.error = error;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiServerStatusResponse apiServerStatusResponse = (ApiServerStatusResponse) o;
    return Objects.equals(this.serverStatus, apiServerStatusResponse.serverStatus) &&
        Objects.equals(this.error, apiServerStatusResponse.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serverStatus, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiServerStatusResponse {\n");
    sb.append("    serverStatus: ").append(toIndentedString(serverStatus)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

