/*
 * owenpeterson.ca
 * This is the server for my personal website.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: owen.a.peterson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ca.owenpeterson.web.api.client.model;

import org.junit.Test;


/**
 * Model tests for ApiDefaultError
 */
public class ApiDefaultErrorTest {
    private final ApiDefaultError model = new ApiDefaultError();

    /**
     * Model tests for ApiDefaultError
     */
    @Test
    public void testApiDefaultError() {
        // TODO: test ApiDefaultError
    }

    /**
     * Test the property 'errorMessage'
     */
    @Test
    public void errorMessageTest() {
        // TODO: test errorMessage
    }

}
