/*
 * owenpeterson.ca
 * This is the server for my personal website.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: owen.a.peterson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ca.owenpeterson.web.api.client.model;

import org.junit.Test;


/**
 * Model tests for ApiServerStatus
 */
public class ApiServerStatusTest {
    private final ApiServerStatus model = new ApiServerStatus();

    /**
     * Model tests for ApiServerStatus
     */
    @Test
    public void testApiServerStatus() {
        // TODO: test ApiServerStatus
    }

    /**
     * Test the property 'databaseStatus'
     */
    @Test
    public void databaseStatusTest() {
        // TODO: test databaseStatus
    }

    /**
     * Test the property 'databaseStartTime'
     */
    @Test
    public void databaseStartTimeTest() {
        // TODO: test databaseStartTime
    }

}
