/*
 * owenpeterson.ca
 * This is the server for my personal website.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: owen.a.peterson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ca.owenpeterson.web.api.client.model;

import org.junit.Test;


/**
 * Model tests for ApiServerStatusResponse
 */
public class ApiServerStatusResponseTest {
    private final ApiServerStatusResponse model = new ApiServerStatusResponse();

    /**
     * Model tests for ApiServerStatusResponse
     */
    @Test
    public void testApiServerStatusResponse() {
        // TODO: test ApiServerStatusResponse
    }

    /**
     * Test the property 'dbStatus'
     */
    @Test
    public void dbStatusTest() {
        // TODO: test dbStatus
    }

}
