services:
  web-api:
    container_name: web-api-container
    build:
        context: ../../
        dockerfile: ./src/docker/Dockerfile
        args:
          - "WAR_FILE=build/libs/web-api.war"
    image: owenpeterson/web-api
    ports:
      - "8080:8080"

  mysql-db:
      container_name: mysql-container
      image: mysql:latest
      restart: always
      environment:
        MYSQL_DATABASE: "web-api-database"
        MYSQL_USER: "user"
        MYSQL_PASSWORD: "password"
        MYSQL_ROOT_PASSWORD: "password"
      ports:
        - "3306:3306"