/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ca.owenpeterson.web.api;

import ca.owenpeterson.web.api.client.model.ApiDefaultError;
import ca.owenpeterson.web.api.client.model.ApiServerStatusResponse;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-02-18T06:47:31.065312200-06:00[America/Chicago]")
@Validated
@Api(value = "web", description = "the web API")
public interface WebApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /web/status
     * Gets the current status of the server.
     *
     * @return the status of the server. (status code 200)
     *         or Default error payload (status code 200)
     */
    @ApiOperation(value = "", nickname = "getServerStatus", notes = "Gets the current status of the server.", response = ApiServerStatusResponse.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "the status of the server.", response = ApiServerStatusResponse.class),
        @ApiResponse(code = 200, message = "Default error payload", response = ApiDefaultError.class) })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/web/status",
        produces = { "application/json" }
    )
    default ResponseEntity<ApiServerStatusResponse> getServerStatus() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"db_status\" : \"db_status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
